
Vagrant.configure("2") do |config|


#Common VM box
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"


# Define Vm1

  config.vm.define "web" do |web|
     web.vm.hostname = "web.local"
      web.vm.network "private_network", ip: "192.168.56.10"
      web.vm.provision "shell", path: "scripts/setup_web.sh"
      web.vm.provider "virtualbox" do |vb|
        vb.name = "web_vm"
        vb.memory = 512
        vb.cpus = 1
      end
  end

# Define VM2

 config.vm.define "db" do |db|
   db.vm.hostname = "db.local"
   db.vm.network "private_network", ip: "192.168.56.11"
   db.vm.provision "shell", path: "scripts/setup_db.sh"
   db.vm.provider "virtualbox" do |vb|
     vb.name = "db_vm"
     vb.memory = "1024"
     vb.cpus = 1
   end
 end

end 
